language: ruby
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: Nqkph/XJVlAk7YZYIT0vUwZK4BLAv3dk26ArPpV1U2AYbOiTi5rUgeRNPHTitcrsKf0yHRAjygfC1WTIYEIyn/1lQYNmtmv4UAv19jQ9VCY1fMWuYnAfCjyiXy8BT8yUglUlqdy8uZn+XuS6N6L3gQ179WWP7eo4JkWPq3wHiWJ0u755ZVZfdmR9Gyr8m3A9VcuB3VrOVfwPe3f7XigBWfRBDBsvHUAsaN2IeUUI3epyAJBn2xOgbPdmzTdWOGRbiHcvx+Ts/pspA7pNsbzz0wB2LR0TC91pUJKr1H0uo4LjLRz/MJs4WkRjXPO0/Lz1Vuer+ClEduJ6CeqqKnx9Q7bEc2YpyQksD8imJCoYd8IrtLmVNi8O9+iQ/R/QMnugvmkWuJRkTNxlNpSTpyvdeiVPxzPkKDfBXuCsW51X43+tg9ImTidQCKs9aBKJG+gRphfKV3M9tJRpyIXMn+UH7zBN2yQAddxKBgf7rntR6ngiEsuORt1io1o9GQwhCvz0WqIOPM7r7zO1lUBe27NAN+s3NPPZoEuXXEdUmzAdop45odSv7bEjCsHGXqAppod2IRwtgbSc6ZiYZzDqaPfGvCLqobPAZocz1y8uc1wVkmQe+hhclvQgtxrmZIloxIwlrthfHDv+D1zP8eobPHe27Wa6kQOi7wDgDVD4BSGcLtE=
sudo: false
exclude:
- vendor
branches:
  only:
  - master
