language: ruby
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: u+neFqL8wL6LYvGwUqhlLum8ciEmt4/jGrWSw9NibBT2iQ93u1t/s5yvCGwYqqHrIoCCo7N+VO34fX7p+WVvgKDtNnU0AA7Br/dhAaam4BYzl0r9vXEGnXjj5/N1jJii9SpH2w5KXER2vHP4C7F/L8s6tzmGv0VtNcMiUQ3lwDSvzbv8N8CKZs7Upnlj+pxPmWsg5B4rzGrQJvPmoSo8mJe0ckTtxGkevFyAxxVSu/3+yOZxJKCRUrpNNfMNBg7VLAMLJC9cdL4a93Fh0vAhy4XT2kaLegAGZT0jlb5Ba6Zs8XgHusFI/4BkBqDDpanU/TaGyEe8ttqdoEb7jb/MTCMN95zTceqR5SOAZ1UwwiPr0Gvq5qfJAqry3ZXCzDP86yFfjeFlPJhx8ClF9kHRl/VYptyS77K8I4c7FS4T3x6e96eCOBLXo16aV7A0wCTIzwohsffWhcnr8yLtlithgRhKajBBoWodd4ki6RW7bwl65lvu6778UmCcxkTjbMOaI8a8LvdwbGaad8fCyDHGrmefbli3M5yd/d6i+8pwRwjyswWihsxJ4nfrr2RmsmhGPLKjUUDP1BX8iBVycczMtMEarFihzXZENKu3xO/Qa5u9nRd8/JU2EuyTHiS77QfPO8infXnPLd1cglIFCn98EXcKRqXLcYy6pNXuLfVkDGY=
sudo: false
exclude:
- vendor
branches:
  only:
  - master
