language: ruby
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: "LVCovgeSBVwo9poQ3MEcWHy90Sj9rPCJBPoewV3KK5f12DkDZ/ruRXjCkfZPzXkERKTkts7ec4TtiLCZAjEtFXa/I0kASjXCnfhXc2S4XeHkirtNV2mgeD2iCsSGYok9JtKOtiXHzawOj1pPoM8svY7S0+Z/yGakCBnO9V25W9JmvIRTKkt+mrrp2ufgWWmE1xOqb5EKrGrjT6VTxi5/+EksxnNkUK2yEKJE7OXgP+2JMNxclVS2J9FbdarKTYY2It2zQWDJu/+qGCXwIHlkY/be7yi6gxuzAfVCy/xV0n7Geit2T6yqIeofkUYb2U2Ql26mxZD31nMNe3XpBQdLNqXrV75j5DWaL1erx+lav3yaC8hvT8d9uTw+pbrkOAxteytnMEMit7IsKwSCJs4h0Vi1MGwymT7Ru9fmHQbjnL8Q+/wpn+9GlZPM+rAmLFm70It64ncNj5iiTPolCXwFmPUADkdWZBy6dSn1P/JqpSZmA75juSb4taiGehwSp6MgTI3jW1GvAtFFMR/mEDim/Z9liExPEfyJW1kZusyV5BVmvb3edfa6uL/j6YEGfG1qr1fPPUgZZSbIjKjCIrd4EeF3y+CYnTsSCwLTeNfBF3qttD7cuwKgBhLhgo4VqBzU4jH+mUsRLWbsvr2d23tiEqan/pUVfCepCSvsRPrJviQ="
sudo: false
exclude:
- vendor
branches:
  only:
  - master
