language: ruby
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: nPX+afXul7CNan3CJdr05yI09gWdJ1bcVpdO3t9/iE4tu9eM2g1I+sQhBGUTQV9Z5e/HAOFSetbktTIKmEHOa4zSsjgbXOhp2Ddos4Sf6WWg0oGvz5h19i+rKUWVezyu7BrA+75cQ7wlvvaUzBix+fZ9wxbdCKIpYPldXpheEmDuy/iWRCaokhaSx44Qr3zkMY3TnVhFX3T2equJ5eWjKylFesJ0WBVvOv4VV/iuodm5yvoGZC/NaPt6uBRE2wky2gS3zAcSIp+gRCBElEgFO94SjHGsBN9/5DIWEDZHHRqyx8gYbWL5WJ+DXDFSEsl+vB/otEQ2xM6sLL3od/QjFYnMhDiRLLUr7xizciUeJ1SYn/DZZyUOrdzvnhezvvVtsNUGaH/OAStCwbP98ijIsyA/j4rneMMqzkQmd4X295hU0BfWWzPQCxbbJXmGkabhI7RrJgoL14A6R+wKjOd2AOy3SCIII+65TKCophSD+fyxa2Ny7EJekpacx0Yzw88v1CDCRlkG2Ghw1tndVzZZDZjKLd7/55c77iwYLMp/EeFoMdRs99yVxw5BfOiRsBeYRrtyOIOBTcpszUPeOvxGPL6QMOc3QNsOMU7zDelHdvsUmHTEeEgcGLpsQ193hn2+VZRLtbEjVr+F0Yc3fGK2rb8YojOKRVVTpbJ1NUE1/n8=
sudo: false
exclude:
- vendor
branches:
  only:
  - master
secure: "aWH4BEb54I08rkRqeV4U1FIcUGykiQYFmLIO4EOYqa56pIQaceoqG8pYAy4wj4zBPL24IVVUgPBdjuWsYhX5ZYbiAdlrE/P0B9wHF5j4ROBPZJEhsfkMLWNC9CO0oOY//Ev8r1uTpw7InPDLwvF2U6O6ALugHoLhlTvd0L7Rgkrzwb363wt6pj/8Fnl24jPiyIPobi6kTnxO8HmoBbi0Wa8R9urwmmzSHa9nDuTFPK0jPvFAPJ408oRGheMGWvy0NMzCcns9LfonkE31w/SrGuPhjb7LwPhlQlIx5QgX232q/56wEUHIJxWEYU1pXJuao0Udc6A8+eFGn6GpH/YlFo/hMT5TT3ZfhuS3IQwCgWPVznwMeyMbcb8IEeIes6Sr6rRSjhm4cr6jDKSkV29Ass20UtvJJ+y8dMSlyWA78Krfs5kT73heUoSjxy9eDeU+RDo4Yo77WWB106Z4O35g8XZn9Eq8bo74QjOJPfQHQO14wjxfqQQhWc1FQgs1FLzjZmekzo+1S4Ui0nA+HfWZc2TpRwq67cTzTZy3fTLcP+m1UvLXypK1TMfkFlR8Uk4s/42mnwRNUS64AGcSPp4/x72oghFLLMvx8Ak2OLTbR/jfQz3KQCHLI5p6a7TJAfKQV9UDps7YznKSwpHi7kPbMyH88xOFufF36vUX5vTn/AA="

